% Read the EWF header row and the L/D–WTO table
raw = readmatrix('Preliminary Sizing.xlsx', 'Range', 'A20:I28');
% ERJ 175 reference point
MTOW_ERJ = 82673;
EWF_ERJ  = 0.564;
LD_ERJ   = 17.5;
EWF = raw(1,2:end);        % EWF values
LD  = raw(2:end,1);        % L/D values
WTO = raw(2:end,2:end);    % takeoff gross weight [lb]

% Carpet-plot layout controls
offset = 3000;   % horizontal separation of successive L/D curves
nref   = 0;      % number of reference divisions on each cheater axis

fig = figure('Color','w', ...
    'Units','pixels', ...
    'Position',[100 100 1600 900]);

ax = axes(fig, ...
    'Position',[0.10 0.15 0.84 0.72]);
hold(ax,'on')
box(ax,'on')
grid(ax,'on')
carpet(EWF, LD, WTO, offset, nref, 'r-', 'b-');
% Convert EWF and L/D to the carpet's horizontal coordinate
[xERJ, ~] = carpetconvert(EWF, LD, WTO, offset, EWF_ERJ, LD_ERJ);

% Add point
hERJ = plot(ax, xERJ, MTOW_ERJ, 'o', ...
    'MarkerSize',12, ...
    'MarkerFaceColor',[0.85 0.20 0.20], ...
    'MarkerEdgeColor','k', ...
    'LineStyle','none');



% EWF labels: retain their current position
carpetlabel(EWF, LD, WTO, offset, nref, ...
    1, 0, 200, -400, ...
    'FontName','Times New Roman', ...
    'FontSize',10, ...
    'Color','k');

% L/D labels: move upward
carpetlabel(EWF, LD, WTO, offset, nref, ...
    0, 1, -300, 1000, ...
    'FontName','Times New Roman', ...
    'FontSize',10, ...
    'Color','k');
hEWF = plot(ax, nan, nan, 'b-', 'LineWidth',1);
hLD  = plot(ax, nan, nan, 'r-', 'LineWidth',1);

lgd = legend(ax, [hEWF hLD, hERJ], ...
    {'$\mathrm{EWF\ Isolines}$', ...
     '$L/D\ \mathrm{Isolines}$', '$\mathrm{ERJ\ 175}$'}, ...
    'Interpreter','latex', ...
    'FontName','Times New Roman', ...
    'FontSize',12, ...
    'Location','northeast', ...
    'Box','on');
ylabel(ax, ' MTOW [10^3 \times lbs]','FontName','Times New Roman', 'FontSize',13, 'Color','k')

set(ax, ...
    'FontName','Times New Roman', ...
    'FontSize',12, ...
    'LineWidth',1.0, ...
    'XColor','k', ...
    'YColor','k', ...
    'GridColor',[0.75 0.75 0.75], ...
    'GridAlpha',0.25, ...
    'Color','w')

axis tight
% Leave breathing room between the carpet and the left/right plot borders
xl = xlim(ax);
xPad = 0.05 * diff(xl);
xlim(ax, xl + [-xPad, xPad]);

% Clean, evenly spaced takeoff-weight ticks
tickStep = 5000;
wTicks = floor(min(WTO(:))/tickStep)*tickStep : ...
         tickStep : ...
         ceil(max(WTO(:))/tickStep)*tickStep;
yticks(ax, wTicks)
yticklabels(ax, string(wTicks/1000))
ylim(ax, [wTicks(1)-0.25*tickStep, wTicks(end)+0.25*tickStep])

% Small amount of space above and below the carpet
ylim(ax, [wTicks(1)-0.25*tickStep, wTicks(end)+0.25*tickStep])
